markdown: kramdown
theme: minima

title: Colorado State Trumpet Guild
repository: https://github.com/enzobarrett/csutrumpetguild.org
timezone: America/Denver
description: Colostate State's Trumpet Guild. Come visit us!
